### ISSUE TITLE
Configuration parameter secret_file is not working

### ISSUE THREAD

**Issue by alex3305** [alex3305/home-assistant-addons#21]
The option `secret_file` isn't working for me. If I write `secret_file: secrets-test.yaml` the addon is still writing inside `secrets.yaml`.

_Originally posted by @ElVit in https://github.com/alex3305/home-assistant-addons/issues/18#issuecomment-790088512_

**Comment by alex3305** [comment]
@ElVit Thanks for reporting this issue. I've improved upon this behaviour with version 1.4.1 and commit b31ed942859f31a7d68b5b553acc97a2ac628a67. However I could not verify this issue. See:

![image](https://user-images.githubusercontent.com/5155694/110202950-e2680380-7e6b-11eb-8583-2f65d687a4ea.png)
![image](https://user-images.githubusercontent.com/5155694/110202993-07f50d00-7e6c-11eb-9721-d45cbeb2268d.png)

Can you please verify this or perhaps elaborate on this issue with your (partial) configuration and the output you're receiving?

**Comment by ElVit** [comment]
@alex3305
I found the cause of my error. In your screenshot you wrote `secrets_file:` but the docu says `secret_file:`. Now it’s working also for me.

**Comment by alex3305** [comment]
@ElVit Thanks for pointing this out and getting back to me! Also very good you've got it working. I've just fixed this in the docs and am closing this issue.
