### ISSUE TITLE
Addon fails to start with option access_logs: true

### ISSUE THREAD

**Issue by fredrikbaberg** [alex3305/home-assistant-addons#22]
Thank you for this addon! I have it running, it works with access to the services I've setup.

Today I tried to set `access_logs: true` in the addon options, which leads to the addon not starting. If I leave it as `false` it works. I've also tried to set the environment variable `TRAEFIK_ACCESSLOG=true` according to https://doc.traefik.io/traefik/reference/static-configuration/env/, with no result.

Could you verify that access logs can be enabled, either through the `access_logs` option or environment variable?

These are the final lines of the output:

```
[11:00:04] INFO: No additional environment variables found
[11:00:04] INFO: Starting Traefik...
[11:00:04] INFO: Running Traefik without env_vars
2021/03/16 11:00:04 command /usr/local/bin/traefik error: yaml: line 23: did not find expected key
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

My settings are as follows:
```
log_level: info
access_logs: true
forwarded_headers_insecure: false
dynamic_configuration_path: /config/traefik/
letsencrypt:
  enabled: false
  resolvers: []
env_vars: []
```

**Comment by alex3305** [comment]
Hi @fredrikbaberg. Thank you for using this add-on and reporting this issue. I've investigated your reported issue and fixed this in the just released 4.0.9 release with 8206f874e57bcdde435be34d3a2391f66dc396bd. Please update and enjoy (excessive) access logging 😉.

I consider this issue closed. If you have any more questions, please reply or open up a new issue.
