### ISSUE TITLE
Question for Rclone

### ISSUE THREAD

**Issue by ElVit** [alex3305/home-assistant-addons#23]
Hi @alex3305 ,
its me again :)

Is it possible to use your rclone addon to copy/sync files from e.g. ftp to homeassistant?

I have a fritzbox router with an attached USB drive. 
I have only the possibility to use SMB or FTP to access the files. 
I would like to backup these files to my homeassistant share directory.
According to my researches for SMB its necessary to mount a share but its also not that easy because of the permission rights, so I will try FTP.

If I understand the DOCS and CONFIG file correct its only possible to backup files from homeassistant to somewhere. Is this correct?

**Comment by alex3305** [comment]
Thanks again for creating an issue. This is a great question. The rclone add-on only provides a one way sync from Home Assistant to a remote. Perhaps the documentation should clarify on this. Until than I will keep this open.

Does this answer your question?

**Comment by ElVit** [comment]
Yes thank you.
I thought that maybe it would be possible somehow with your addon because of this line from your README:

> Rclone ("rsync for cloud storage") is a command line program to sync files and directories _**to and from**_ different cloud storage providers.

But its ok, I will looking for an other way to reach my goal.

**Comment by jd1900** [comment]
It is really confusing.

I though I could use it to mount a remote into a HA folder.
However, it just copies backups files, which is useless to me.
It would be better to allow to just mount remote dirs locally using rsync.

Furthermore, it started to delete my remote files as it started.

It should be much better explained. This is not a rsync addon, it is a backup addon using rsync, which is totally different.

**Comment by alex3305** [comment]
@ElVit Thanks again for the input. I've updated the readme.
