### ISSUE TITLE
Upgrade Traefik

### ISSUE THREAD

**Issue by vladgh** [alex3305/home-assistant-addons#27]
Would be possible to upgrade Traefik to 2.5.6?
Thank you for this great addon!

**Comment by alex3305** [comment]
As you wish, kind sir: 9932b92aadb58f531a92ffd24d4dd25679ce838b.

As a slight note and future reference. I have stopped using this add-on. I've migrated my Home Assistant box to unRAID and I'm running HA OS in a VM and Traefik in a separate Docker container.

**Comment by vladgh** [comment]
Thank you, I appreciate it. Also, thanks for letting me know about the project. This makes my choice easier because I was torn between using traefik in it's own LXC container in Proxmox and this addon for home assistant which I have on Raspberry Pi 4.
