### ISSUE TITLE
ModSecurity plugin

### ISSUE THREAD

**Issue by thetux07** [alex3305/home-assistant-addons#28]
Hello.
it's possible to add Modsecurity plugin to Traefik?
https://github.com/acouvreur/traefik-modsecurity-plugin
thank you
best regards

**Comment by alex3305** [comment]
Hi,

To be honest, I don't see the point of this plugin. As you could apply all those rules yourself. Also you'll need `owasp/modsecurity-crs` running somewhere in the background, so this would create an unwanted dependency. And last but not least, it seems a very unstable, fairly new plugin. 

So, no. I'm not going to add this plugin.
