### ISSUE TITLE
proxy pass

### ISSUE THREAD

**Issue by thetux07** [alex3305/home-assistant-addons#30]
hello,
it's possible to create an proxy_pass ?
for my exemple if i would like call https://domain/toto i would like to redirect to 192.168.1.2:6789/toto 
if yes, have you an exemple ?
thank you
regards

**Comment by alex3305** [comment]
Hi,

This is already documented within the [documentation](https://github.com/alex3305/home-assistant-addons/blob/master/traefik/DOCS.md#example-dynamic-traefik-configuration).

**Comment by thetux07** [comment]
ok thank you but it's to light

for exemple, i had this line but don't work


    testRouter:
      rule: "Host(`hadomain.duckdns.org`) && Path(`/test`)"
      entryPoints: ["web-secure"]
      service: testService

    testService:
      loadBalancer:
        servers:
          - url: "http://192.168.10.2:1234/test"
where i wrong ?
thank you
