### ISSUE TITLE
Make Rclone addon local folder configurable

### ISSUE THREAD

**Issue by kapu-** [alex3305/home-assistant-addons#31]
It seems that the Rclone addon clones only the /backup/ directory by default. Could the cloned directory be configurable? I would like to use this to backup camera recording files. Thanks!

**Comment by alex3305** [comment]
Hi @kapu-,

Thanks for your suggestion. If I understand correctly you would like to (for instance) backup the `/share/`directory instead of the `/backup/` directory? Of course this would be possible, but IMHO would defeat the purpose of the add-on, which is to backup the Home Assistant backups.

Would you care to elaborate, so I can think about this?

Thanks! ❤️

**Comment by alex3305** [comment]
Hi @kapu-,

I'm still open to hear what you think about my proposal and discuss it with you. But since this issue is getting stale without any input, I'm going to close this for now 😢.  If you reply I will open this issue if necessary. Thanks again ❤️.

**Comment by kapu-** [comment]
Sorry I have forgotten to answer. My thinking is that as there are also other add-ons that are only for backing up Home Assistant configurations etc. (I am using Home Assistant Google Drive Backup) this add-on could be more versatile tool by allowing user to back up more / different thing (like camera recordings). I haven't found other add-ons that can backup other data than config backups so this add-on could become unique by letting user to configure what folders they want to backup.

**Comment by alex3305** [comment]
Thanks for your response, as you can see I've reopened this issue to discuss this further with you.

The following directories are already available with full read/write access:
* `/backup/`
* `/config/`
* `/share/`

Perhaps your use-case is already viable with the current setup? Can you test this? Or do you also want another directory exposed?

**Comment by alex3305** [comment]
I'm going to close this issue again as per inactivity.
