### ISSUE TITLE
Access log location

### ISSUE THREAD

**Issue by stefaanv** [alex3305/home-assistant-addons#47]
Hi,
Thank you for this add-on.
After enabling the access log, where can I find it ?

```
 Add-on version: 4.2.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 11.0  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.10.5
 Home Assistant Supervisor: 2023.10.1
```

Stefaan

**Comment by alex3305** [comment]
Hi,

I'm sorry I didn't get back to you sooner. I lost sight of this issue. AFAIK the access log should show up in the add-on logging.
